$axure.loadCurrentPage({
  "url":"newcustomer.jsp",
  "generationDate":new Date(1417055439094.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ec4f6d7b465c46ed942c1cdbe00bce35",
    "type":"Axure:Page",
    "name":"newcustomer",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ecb2ef40ea414cd28c362080db020398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":810,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7997f24cee64bd4a3514c6d582c15e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":810,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"da204e3e51ed4040a97a529394b51bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":160},
            "size":{
              "width":550,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368f1261a2124d3f85e071930fffbd06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":160},
                "size":{
                  "width":550,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/newcustomer/u2.png"}},
{
          "id":"d3162af0ea714fadb445e8a14b6db052",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":359,
              "y":172},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6714679bb358415eb1f3a8bbed15db13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":359,
                  "y":172},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1111c99b47b4bcca10c7217a882f532",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":236,
              "y":272},
            "size":{
              "width":118,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd723f53d3647d1b0d2273b1a248535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":236,
                  "y":272},
                "size":{
                  "width":118,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"410a3cee01b4487c9f660720b318fea8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":236,
              "y":409},
            "size":{
              "width":47,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91dbd0ab976047a6a9d10993e2dc446a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":236,
                  "y":409},
                "size":{
                  "width":47,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cd6eb2c4adb46ba9962b8d239c17848",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":237,
              "y":454},
            "size":{
              "width":71,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0954498933b4af9b3a70fe96e6baab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":237,
                  "y":454},
                "size":{
                  "width":71,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2c64178c16b46feb453dae5b572fa67",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":426,
              "y":269},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"a3af1d8914664b0db65f522f694b760d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":426,
              "y":311},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"892010aadecf427aa6e628f4a626042f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":426,
              "y":451},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"9a68768f37a04a2f97e98b7be3d40df6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":290,
              "y":506},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"aaf474d855e44e9592b37c93f0727c2a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":460,
              "y":506},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"141eab26cf3b42359386773a783997d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":236,
              "y":318},
            "size":{
              "width":140,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"420e6fd0c4c44dd89520c612cf9fa9dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":236,
                  "y":318},
                "size":{
                  "width":140,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"020a6978b0194e2f89584a091caadcd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":234,
              "y":360},
            "size":{
              "width":130,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c7030318f3499ca611434410a5b4d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":234,
                  "y":360},
                "size":{
                  "width":130,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"465154b4d0184c95a765b2cb833bc512",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":426,
              "y":357},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"7904fa73a0e846cb8c2e6888ef5ea4cf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":426,
              "y":405},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"e6e57a46c94644f8b0f5490d6ddb14e3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":290,
              "y":222},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d3ec40b414442af8c94c70265a05495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":290,
                  "y":222},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Text Field),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(HTML Button),<br>(HTML Button),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Shape),<br>Hide (Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(HTML Button),<br>(HTML Button)",
                      "objectsToFades":[{
                          "objectPath":["7904fa73a0e846cb8c2e6888ef5ea4cf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["465154b4d0184c95a765b2cb833bc512"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["020a6978b0194e2f89584a091caadcd7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["141eab26cf3b42359386773a783997d0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aaf474d855e44e9592b37c93f0727c2a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9a68768f37a04a2f97e98b7be3d40df6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["892010aadecf427aa6e628f4a626042f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a3af1d8914664b0db65f522f694b760d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f2c64178c16b46feb453dae5b572fa67"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4cd6eb2c4adb46ba9962b8d239c17848"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["410a3cee01b4487c9f660720b318fea8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d1111c99b47b4bcca10c7217a882f532"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["65d5cd4a7e5e4e82847124e47b618722"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3d534806e1ae4dd6b76833701b6e5447"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["867cb2a46d6240ab8035f9efb5fd8785"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cd900a7561974b55b57ed1f45aacbd07"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["eb558cc0a99d48039f5d103a64746935"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1d99610200f8441b91a2e0f3f9157846"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["86428c6c5cb44022850fee15f50cb1b0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7e1080d350d24af0a9eb7a953783518d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7a6523fed15643e181077b2e33079b89"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f1e6183f5f914616a63cc5484b1fc0ee"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2b187a6f9dff4c96b79b91a20437a06e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["df4145faa3994c5fbf9e7d28aade01c1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6b86e8df767141668c9048ddedd2a70c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f124550e722140199146f434bdbd163c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ee449c70b9d34daba188d4b65f9991fb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["594662f77b514bdaa8ffc73daecc5f1a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"5007436175594a2292f9f76e9d466b3a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":500,
              "y":222},
            "size":{
              "width":100,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25e4c7df6f26445a81fe2f87873985f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":500,
                  "y":222},
                "size":{
                  "width":100,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (HTML Button),<br>(HTML Button),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>Hide (Text Field),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(HTML Button),<br>(HTML Button),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Shape)",
                      "objectsToFades":[{
                          "objectPath":["594662f77b514bdaa8ffc73daecc5f1a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ee449c70b9d34daba188d4b65f9991fb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f124550e722140199146f434bdbd163c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6b86e8df767141668c9048ddedd2a70c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["df4145faa3994c5fbf9e7d28aade01c1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2b187a6f9dff4c96b79b91a20437a06e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f1e6183f5f914616a63cc5484b1fc0ee"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7a6523fed15643e181077b2e33079b89"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7e1080d350d24af0a9eb7a953783518d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["86428c6c5cb44022850fee15f50cb1b0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1d99610200f8441b91a2e0f3f9157846"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["eb558cc0a99d48039f5d103a64746935"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cd900a7561974b55b57ed1f45aacbd07"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["867cb2a46d6240ab8035f9efb5fd8785"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3d534806e1ae4dd6b76833701b6e5447"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["65d5cd4a7e5e4e82847124e47b618722"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7904fa73a0e846cb8c2e6888ef5ea4cf"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["465154b4d0184c95a765b2cb833bc512"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["020a6978b0194e2f89584a091caadcd7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["141eab26cf3b42359386773a783997d0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aaf474d855e44e9592b37c93f0727c2a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9a68768f37a04a2f97e98b7be3d40df6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["892010aadecf427aa6e628f4a626042f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a3af1d8914664b0db65f522f694b760d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f2c64178c16b46feb453dae5b572fa67"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4cd6eb2c4adb46ba9962b8d239c17848"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["410a3cee01b4487c9f660720b318fea8"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d1111c99b47b4bcca10c7217a882f532"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"65d5cd4a7e5e4e82847124e47b618722",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":274},
            "size":{
              "width":62,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf35d1b2bca49289a184862c61f77c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":274},
                "size":{
                  "width":62,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d534806e1ae4dd6b76833701b6e5447",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":313},
            "size":{
              "width":117,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b83e6f7594ee4d4ebadc1810617d951c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":313},
                "size":{
                  "width":117,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"867cb2a46d6240ab8035f9efb5fd8785",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":348},
            "size":{
              "width":58,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"270dce66650e4d8ea73db5a78777555c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":348},
                "size":{
                  "width":58,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd900a7561974b55b57ed1f45aacbd07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":383},
            "size":{
              "width":34,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb9daf5be594e9bbd32f0111c3d262b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":383},
                "size":{
                  "width":34,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb558cc0a99d48039f5d103a64746935",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":416},
            "size":{
              "width":57,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac04baf29f104800920c92c1dc473e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":416},
                "size":{
                  "width":57,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d99610200f8441b91a2e0f3f9157846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":452},
            "size":{
              "width":47,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4435075789749e6b55ec5cda77e3efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":452},
                "size":{
                  "width":47,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86428c6c5cb44022850fee15f50cb1b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":252,
              "y":487},
            "size":{
              "width":71,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca7eb4d8b11488ca83e9af644387f17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":252,
                  "y":487},
                "size":{
                  "width":71,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e1080d350d24af0a9eb7a953783518d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":272},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"7a6523fed15643e181077b2e33079b89",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":308},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"f1e6183f5f914616a63cc5484b1fc0ee",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":342},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"2b187a6f9dff4c96b79b91a20437a06e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":377},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"df4145faa3994c5fbf9e7d28aade01c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":412},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"6b86e8df767141668c9048ddedd2a70c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":447},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"f124550e722140199146f434bdbd163c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":414,
              "y":482},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"ee449c70b9d34daba188d4b65f9991fb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":334,
              "y":528},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"594662f77b514bdaa8ffc73daecc5f1a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":490,
              "y":528},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"045c3da53abc462fa0ff2c03bd1d57a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":65,
              "y":79},
            "size":{
              "width":175,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f36ba2b5ff24e4592b0a692b0336606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":65,
                  "y":79},
                "size":{
                  "width":175,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"607bc1dcf4864998bf720ab0ad81ec23",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":250,
              "y":70},
            "size":{
              "width":520,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62665f4f06c248ebaac237a304419cb4",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8cfdf9acaad0440dad93ef6f3fb0443c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e158ea0dbe1541ddb414025654583f6d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"1ab781a8024945d6ae3e66f0b36018d6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75d62b6900644fe194feab8f47ea398f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":390,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"37c1e5d280eb4ccc8b64a11437a47d0b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c08e8235b5645da8a2e194890d84d31",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open index in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"index.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"f855abd421834c1da41d6dd155bbdcf8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e3789e442b541ae873a58cb09645826",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open customer in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"customer.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}}]},
{
              "id":"22ce05733b7f4d299f94151901f1976a",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":50},
                "size":{
                  "width":130,
                  "height":142},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d4ad5e330644aad90d7d48317c35454",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0fc1e7e76ecd4da78def466c588ebfd4",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1e42c4eb409a4edc9b8de7d2e51d5f60",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open payment in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"payment.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"4114efea212d418ea224c7689e3b5aa1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b77985cf037e4280b904afe51ad6f4e3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open inventory in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"inventory.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"de7859ffdd2c4463a5f5c0c6e3f9e43b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":130,
                          "height":50},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c7bb5b97286e446dbb67a0dcb2aa5c90",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":130,
                              "height":50},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open newcustomer in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"newcustomer.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u14.png"}}]}],
              "parentCellId":"8cfdf9acaad0440dad93ef6f3fb0443c"},
{
              "id":"359416ef314646fcaaae3be1bdacbae6",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":50},
                "size":{
                  "width":131,
                  "height":171},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8923fe17d0504332918a1407f3cd83a3",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":131,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84bc1f307bb04b8da58bd738cd0ef8ba",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":131,
                          "height":41},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"430ec906c4614db6977d541360048c97",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":131,
                              "height":41},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open profit in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"profit.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u26.png"}},
{
                      "id":"eaf466695ad845de862e7c8a4c9af997",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":131,
                          "height":38},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d014736090964eef8c9b18f4ef47da3a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":41},
                            "size":{
                              "width":131,
                              "height":38},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open top products in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"top_products.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u28.png"}},
{
                      "id":"6e793aa695384582a11950a06e1d0ecb",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7e4275db74ae407db84fa89232783a27",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":79},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open comparison in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"comparison.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u30.png"}},
{
                      "id":"a2d045885b834a1294436b0a301e0d6d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"68f55552a1794131a898dee7201852e6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":125},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open businese in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"businese.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u32.png"}}]}],
              "parentCellId":"1ab781a8024945d6ae3e66f0b36018d6"}]}]}},
  "masters":{
},
  "objectPaths":{
    "ecb2ef40ea414cd28c362080db020398":{
      "scriptId":"u0"},
    "f7997f24cee64bd4a3514c6d582c15e3":{
      "scriptId":"u1"},
    "da204e3e51ed4040a97a529394b51bc1":{
      "scriptId":"u2"},
    "368f1261a2124d3f85e071930fffbd06":{
      "scriptId":"u3"},
    "d3162af0ea714fadb445e8a14b6db052":{
      "scriptId":"u4"},
    "6714679bb358415eb1f3a8bbed15db13":{
      "scriptId":"u5"},
    "d1111c99b47b4bcca10c7217a882f532":{
      "scriptId":"u6"},
    "7bd723f53d3647d1b0d2273b1a248535":{
      "scriptId":"u7"},
    "410a3cee01b4487c9f660720b318fea8":{
      "scriptId":"u8"},
    "91dbd0ab976047a6a9d10993e2dc446a":{
      "scriptId":"u9"},
    "4cd6eb2c4adb46ba9962b8d239c17848":{
      "scriptId":"u10"},
    "e0954498933b4af9b3a70fe96e6baab3":{
      "scriptId":"u11"},
    "f2c64178c16b46feb453dae5b572fa67":{
      "scriptId":"u12"},
    "a3af1d8914664b0db65f522f694b760d":{
      "scriptId":"u13"},
    "892010aadecf427aa6e628f4a626042f":{
      "scriptId":"u14"},
    "9a68768f37a04a2f97e98b7be3d40df6":{
      "scriptId":"u15"},
    "aaf474d855e44e9592b37c93f0727c2a":{
      "scriptId":"u16"},
    "141eab26cf3b42359386773a783997d0":{
      "scriptId":"u17"},
    "420e6fd0c4c44dd89520c612cf9fa9dc":{
      "scriptId":"u18"},
    "020a6978b0194e2f89584a091caadcd7":{
      "scriptId":"u19"},
    "71c7030318f3499ca611434410a5b4d7":{
      "scriptId":"u20"},
    "465154b4d0184c95a765b2cb833bc512":{
      "scriptId":"u21"},
    "7904fa73a0e846cb8c2e6888ef5ea4cf":{
      "scriptId":"u22"},
    "e6e57a46c94644f8b0f5490d6ddb14e3":{
      "scriptId":"u23"},
    "2d3ec40b414442af8c94c70265a05495":{
      "scriptId":"u24"},
    "5007436175594a2292f9f76e9d466b3a":{
      "scriptId":"u25"},
    "25e4c7df6f26445a81fe2f87873985f6":{
      "scriptId":"u26"},
    "65d5cd4a7e5e4e82847124e47b618722":{
      "scriptId":"u27"},
    "caf35d1b2bca49289a184862c61f77c9":{
      "scriptId":"u28"},
    "3d534806e1ae4dd6b76833701b6e5447":{
      "scriptId":"u29"},
    "b83e6f7594ee4d4ebadc1810617d951c":{
      "scriptId":"u30"},
    "867cb2a46d6240ab8035f9efb5fd8785":{
      "scriptId":"u31"},
    "270dce66650e4d8ea73db5a78777555c":{
      "scriptId":"u32"},
    "cd900a7561974b55b57ed1f45aacbd07":{
      "scriptId":"u33"},
    "4fb9daf5be594e9bbd32f0111c3d262b":{
      "scriptId":"u34"},
    "eb558cc0a99d48039f5d103a64746935":{
      "scriptId":"u35"},
    "ac04baf29f104800920c92c1dc473e19":{
      "scriptId":"u36"},
    "1d99610200f8441b91a2e0f3f9157846":{
      "scriptId":"u37"},
    "a4435075789749e6b55ec5cda77e3efe":{
      "scriptId":"u38"},
    "86428c6c5cb44022850fee15f50cb1b0":{
      "scriptId":"u39"},
    "fca7eb4d8b11488ca83e9af644387f17":{
      "scriptId":"u40"},
    "7e1080d350d24af0a9eb7a953783518d":{
      "scriptId":"u41"},
    "7a6523fed15643e181077b2e33079b89":{
      "scriptId":"u42"},
    "f1e6183f5f914616a63cc5484b1fc0ee":{
      "scriptId":"u43"},
    "2b187a6f9dff4c96b79b91a20437a06e":{
      "scriptId":"u44"},
    "df4145faa3994c5fbf9e7d28aade01c1":{
      "scriptId":"u45"},
    "6b86e8df767141668c9048ddedd2a70c":{
      "scriptId":"u46"},
    "f124550e722140199146f434bdbd163c":{
      "scriptId":"u47"},
    "ee449c70b9d34daba188d4b65f9991fb":{
      "scriptId":"u48"},
    "594662f77b514bdaa8ffc73daecc5f1a":{
      "scriptId":"u49"},
    "045c3da53abc462fa0ff2c03bd1d57a6":{
      "scriptId":"u50"},
    "3f36ba2b5ff24e4592b0a692b0336606":{
      "scriptId":"u51"},
    "607bc1dcf4864998bf720ab0ad81ec23":{
      "scriptId":"u52"},
    "62665f4f06c248ebaac237a304419cb4":{
      "scriptId":"u53"},
    "37c1e5d280eb4ccc8b64a11437a47d0b":{
      "scriptId":"u54"},
    "2c08e8235b5645da8a2e194890d84d31":{
      "scriptId":"u55"},
    "f855abd421834c1da41d6dd155bbdcf8":{
      "scriptId":"u56"},
    "9e3789e442b541ae873a58cb09645826":{
      "scriptId":"u57"},
    "8cfdf9acaad0440dad93ef6f3fb0443c":{
      "scriptId":"u58"},
    "e158ea0dbe1541ddb414025654583f6d":{
      "scriptId":"u59"},
    "1ab781a8024945d6ae3e66f0b36018d6":{
      "scriptId":"u60"},
    "75d62b6900644fe194feab8f47ea398f":{
      "scriptId":"u61"},
    "22ce05733b7f4d299f94151901f1976a":{
      "scriptId":"u62"},
    "5d4ad5e330644aad90d7d48317c35454":{
      "scriptId":"u63"},
    "0fc1e7e76ecd4da78def466c588ebfd4":{
      "scriptId":"u64"},
    "1e42c4eb409a4edc9b8de7d2e51d5f60":{
      "scriptId":"u65"},
    "4114efea212d418ea224c7689e3b5aa1":{
      "scriptId":"u66"},
    "b77985cf037e4280b904afe51ad6f4e3":{
      "scriptId":"u67"},
    "de7859ffdd2c4463a5f5c0c6e3f9e43b":{
      "scriptId":"u68"},
    "c7bb5b97286e446dbb67a0dcb2aa5c90":{
      "scriptId":"u69"},
    "359416ef314646fcaaae3be1bdacbae6":{
      "scriptId":"u70"},
    "8923fe17d0504332918a1407f3cd83a3":{
      "scriptId":"u71"},
    "84bc1f307bb04b8da58bd738cd0ef8ba":{
      "scriptId":"u72"},
    "430ec906c4614db6977d541360048c97":{
      "scriptId":"u73"},
    "eaf466695ad845de862e7c8a4c9af997":{
      "scriptId":"u74"},
    "d014736090964eef8c9b18f4ef47da3a":{
      "scriptId":"u75"},
    "6e793aa695384582a11950a06e1d0ecb":{
      "scriptId":"u76"},
    "7e4275db74ae407db84fa89232783a27":{
      "scriptId":"u77"},
    "a2d045885b834a1294436b0a301e0d6d":{
      "scriptId":"u78"},
    "68f55552a1794131a898dee7201852e6":{
      "scriptId":"u79"}}});