.jsp$axure.loadCurrentPage({
  "url":"top_products.jsp",
  "generationDate":new Date(1417055439614.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1563e848ca094b0cbf56e7344ca1aa26",
    "type":"Axure:Page",
    "name":"top products",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"880871e375594a7c8cf6fad0b9cc9d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":810,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b256716f6747bd9ca3cea0c40a859b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":810,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"2d667260911545db8c3bfc3b214c44aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":160},
            "size":{
              "width":530,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d76dd78cae14968a5864ca19329bd4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":160},
                "size":{
                  "width":530,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/top_products/u2.png"}},
{
          "id":"c7ab31a8c6e0483aad77d43555eed6c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":180},
            "size":{
              "width":154,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"319dcac0c728445d89c75841a0356ce0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":180},
                "size":{
                  "width":154,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d55c63e9d9394b11a63756b075ba8daa",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":230},
            "size":{
              "width":200,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0802b1ac44b840f5bb0247e03a0b45aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c035ccfcba904a528df2fabc0118e111",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u7.png"}},
{
              "id":"60d330785160423aa26d4043589f187d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":58}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa42547a7e5141358115c2e407bedde6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":58}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u11.png"}},
{
              "id":"57ff38b61f93461fb5cefbf81a11d118",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":88},
                "size":{
                  "width":100,
                  "height":62}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"acf2eda75ab244029b24f0130fb4498b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":62}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u15.png"}},
{
              "id":"02dc5b9253404fe0903412260d299ae4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c25e839c7c74046bdc42e8cb557803d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u9.png"}},
{
              "id":"2e71386fdea24c679b179def874cae33",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":58}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83275639f66b48828e18a11226559d7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":58}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u13.png"}},
{
              "id":"2c42fa7c2716472887b4cbb7293b630f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":88},
                "size":{
                  "width":100,
                  "height":62}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cf2728d694943bf9610819266674796",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":62}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u17.png"}},
{
              "id":"0dfa2288367248f199d8884b540f0fd9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"973e30d4ba1343cfaf8f69ff814def6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u19.png"}},
{
              "id":"78a4588c9cc3430e83d1da2fc81bb5ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6882565b16ae4f09a357ce57665dd079",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u21.png"}}]},
{
          "id":"bc36e5b4c634458288b36fce272dc817",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":230},
            "size":{
              "width":200,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7d06d966db41f1a73a35f914fa900d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7f98dad315b4a5a9f2525e3518a2470",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u7.png"}},
{
              "id":"70ab6ca1968c46848218218f4be8bcd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":58}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34ec7c64304c4910b6b02ac67ac94d90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":58}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u11.png"}},
{
              "id":"ce4a9be0eb2243b38057867d07e28fd0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":88},
                "size":{
                  "width":100,
                  "height":62}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9d407eb09c4428a99af44a44ec15eff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":62}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u15.png"}},
{
              "id":"1fcc828b46d64789a11aad988008f953",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9db951282314665af42acb7b2b26501",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u9.png"}},
{
              "id":"744b1546a93e42bfa9d3e4da29982ee1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":58}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6baf04f84cff4ae6a631c92813f4e360",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":58}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u13.png"}},
{
              "id":"764ac2e42dee4ded84f0d34a4d97c366",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":88},
                "size":{
                  "width":100,
                  "height":62}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c37350d31604094b822027cffba41c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":62}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u17.png"}},
{
              "id":"3af5ed7d46d04bbd887f85009c43046d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a65cca0dd77a4899b2cb7e8bdb12a96e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u19.png"}},
{
              "id":"c597357680c3409d85dd9960fd1ef60b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7a0ee232368492d8d5d0e4ddf6929d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":150},
                    "size":{
                      "width":100,
                      "height":80}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u21.png"}}]},
{
          "id":"99a5443a39c14c8cac67239d8b0a392e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":65,
              "y":79},
            "size":{
              "width":175,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8921fa5301a34d3e99cdda7c33710e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":65,
                  "y":79},
                "size":{
                  "width":175,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3b24c800a0a4db0aa49aa2b5ed94ac8",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":250,
              "y":70},
            "size":{
              "width":520,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d84f1bc6342342b4a41040fea17b557f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46e70354700c4b8784b39cb56efd1517",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f64c55d1a3214e12a0bb91941ceabbe6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"d10c9ca64c454909b65c8cb0b3df357a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab980e96dd244e71b327a4d10f58f0db",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":390,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"e2b47f27510249bba2c93a5b63b7c518",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5686c6b7626448cebde14d39bdfe7254",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open index in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"index.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"82afd44d5d674228b1bd59c7397cbf7e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ca70e2b78dd4d239c5f7cd3b0c73e63",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open customer in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"customer.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}}]},
{
              "id":"72fafd857a76472399ff7f9f00d91c88",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":50},
                "size":{
                  "width":130,
                  "height":142},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f3f0a700b4443219ab0aa35f8c02e70",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf11b9dfd36d4c38bff2c6550b0497a1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"406e7fd361a8493c8f9310117019d9f6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open payment in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"payment.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"f8d1cedcef6a4fc3b82fa5ed8a3f8be3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e32e5cc3387a44f492a66049fa8b5609",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open inventory in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"inventory.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"e3f0e974b91647c9a00436873296ad26",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":130,
                          "height":50},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"667bc86873454e72b530c9f09451f137",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":130,
                              "height":50},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open newcustomer in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"newcustomer.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u14.png"}}]}],
              "parentCellId":"46e70354700c4b8784b39cb56efd1517"},
{
              "id":"aa445dd8b54c4eefbbac1469669c11d9",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":50},
                "size":{
                  "width":131,
                  "height":171},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"10c1cfe1b0de494f8079eceec9c7355f",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":131,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46134f2218234b6792cf4891adc4b44a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":131,
                          "height":41},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"178e7823e00c47309bc0671622af3577",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":131,
                              "height":41},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open profit in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"profit.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u26.png"}},
{
                      "id":"4bde9c78541c4e08868145e4ca167d9a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":131,
                          "height":38},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3974c375e9eb40ef96c496f3bacb734a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":41},
                            "size":{
                              "width":131,
                              "height":38},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open top products in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"top_products.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u28.png"}},
{
                      "id":"d2c86faa7b684c8080e6be4655eab356",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2391967baac84a799ecef0465cd7d4b3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":79},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open comparison in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"comparison.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u30.png"}},
{
                      "id":"f73519e370d34195ae6bbee5ad4d44ca",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1e26c14b9e3a4a2ca43acecd56f3b925",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":125},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open businese in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"businese.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u32.png"}}]}],
              "parentCellId":"d10c9ca64c454909b65c8cb0b3df357a"}]}]}},
  "masters":{
},
  "objectPaths":{
    "880871e375594a7c8cf6fad0b9cc9d30":{
      "scriptId":"u0"},
    "a3b256716f6747bd9ca3cea0c40a859b":{
      "scriptId":"u1"},
    "2d667260911545db8c3bfc3b214c44aa":{
      "scriptId":"u2"},
    "5d76dd78cae14968a5864ca19329bd4b":{
      "scriptId":"u3"},
    "c7ab31a8c6e0483aad77d43555eed6c8":{
      "scriptId":"u4"},
    "319dcac0c728445d89c75841a0356ce0":{
      "scriptId":"u5"},
    "d55c63e9d9394b11a63756b075ba8daa":{
      "scriptId":"u6"},
    "0802b1ac44b840f5bb0247e03a0b45aa":{
      "scriptId":"u7"},
    "c035ccfcba904a528df2fabc0118e111":{
      "scriptId":"u8"},
    "02dc5b9253404fe0903412260d299ae4":{
      "scriptId":"u9"},
    "7c25e839c7c74046bdc42e8cb557803d":{
      "scriptId":"u10"},
    "60d330785160423aa26d4043589f187d":{
      "scriptId":"u11"},
    "fa42547a7e5141358115c2e407bedde6":{
      "scriptId":"u12"},
    "2e71386fdea24c679b179def874cae33":{
      "scriptId":"u13"},
    "83275639f66b48828e18a11226559d7b":{
      "scriptId":"u14"},
    "57ff38b61f93461fb5cefbf81a11d118":{
      "scriptId":"u15"},
    "acf2eda75ab244029b24f0130fb4498b":{
      "scriptId":"u16"},
    "2c42fa7c2716472887b4cbb7293b630f":{
      "scriptId":"u17"},
    "1cf2728d694943bf9610819266674796":{
      "scriptId":"u18"},
    "0dfa2288367248f199d8884b540f0fd9":{
      "scriptId":"u19"},
    "973e30d4ba1343cfaf8f69ff814def6a":{
      "scriptId":"u20"},
    "78a4588c9cc3430e83d1da2fc81bb5ad":{
      "scriptId":"u21"},
    "6882565b16ae4f09a357ce57665dd079":{
      "scriptId":"u22"},
    "bc36e5b4c634458288b36fce272dc817":{
      "scriptId":"u23"},
    "4f7d06d966db41f1a73a35f914fa900d":{
      "scriptId":"u24"},
    "e7f98dad315b4a5a9f2525e3518a2470":{
      "scriptId":"u25"},
    "1fcc828b46d64789a11aad988008f953":{
      "scriptId":"u26"},
    "c9db951282314665af42acb7b2b26501":{
      "scriptId":"u27"},
    "70ab6ca1968c46848218218f4be8bcd4":{
      "scriptId":"u28"},
    "34ec7c64304c4910b6b02ac67ac94d90":{
      "scriptId":"u29"},
    "744b1546a93e42bfa9d3e4da29982ee1":{
      "scriptId":"u30"},
    "6baf04f84cff4ae6a631c92813f4e360":{
      "scriptId":"u31"},
    "ce4a9be0eb2243b38057867d07e28fd0":{
      "scriptId":"u32"},
    "f9d407eb09c4428a99af44a44ec15eff":{
      "scriptId":"u33"},
    "764ac2e42dee4ded84f0d34a4d97c366":{
      "scriptId":"u34"},
    "6c37350d31604094b822027cffba41c3":{
      "scriptId":"u35"},
    "3af5ed7d46d04bbd887f85009c43046d":{
      "scriptId":"u36"},
    "a65cca0dd77a4899b2cb7e8bdb12a96e":{
      "scriptId":"u37"},
    "c597357680c3409d85dd9960fd1ef60b":{
      "scriptId":"u38"},
    "f7a0ee232368492d8d5d0e4ddf6929d7":{
      "scriptId":"u39"},
    "99a5443a39c14c8cac67239d8b0a392e":{
      "scriptId":"u40"},
    "8921fa5301a34d3e99cdda7c33710e51":{
      "scriptId":"u41"},
    "f3b24c800a0a4db0aa49aa2b5ed94ac8":{
      "scriptId":"u42"},
    "d84f1bc6342342b4a41040fea17b557f":{
      "scriptId":"u43"},
    "e2b47f27510249bba2c93a5b63b7c518":{
      "scriptId":"u44"},
    "5686c6b7626448cebde14d39bdfe7254":{
      "scriptId":"u45"},
    "82afd44d5d674228b1bd59c7397cbf7e":{
      "scriptId":"u46"},
    "4ca70e2b78dd4d239c5f7cd3b0c73e63":{
      "scriptId":"u47"},
    "46e70354700c4b8784b39cb56efd1517":{
      "scriptId":"u48"},
    "f64c55d1a3214e12a0bb91941ceabbe6":{
      "scriptId":"u49"},
    "d10c9ca64c454909b65c8cb0b3df357a":{
      "scriptId":"u50"},
    "ab980e96dd244e71b327a4d10f58f0db":{
      "scriptId":"u51"},
    "72fafd857a76472399ff7f9f00d91c88":{
      "scriptId":"u52"},
    "0f3f0a700b4443219ab0aa35f8c02e70":{
      "scriptId":"u53"},
    "bf11b9dfd36d4c38bff2c6550b0497a1":{
      "scriptId":"u54"},
    "406e7fd361a8493c8f9310117019d9f6":{
      "scriptId":"u55"},
    "f8d1cedcef6a4fc3b82fa5ed8a3f8be3":{
      "scriptId":"u56"},
    "e32e5cc3387a44f492a66049fa8b5609":{
      "scriptId":"u57"},
    "e3f0e974b91647c9a00436873296ad26":{
      "scriptId":"u58"},
    "667bc86873454e72b530c9f09451f137":{
      "scriptId":"u59"},
    "aa445dd8b54c4eefbbac1469669c11d9":{
      "scriptId":"u60"},
    "10c1cfe1b0de494f8079eceec9c7355f":{
      "scriptId":"u61"},
    "46134f2218234b6792cf4891adc4b44a":{
      "scriptId":"u62"},
    "178e7823e00c47309bc0671622af3577":{
      "scriptId":"u63"},
    "4bde9c78541c4e08868145e4ca167d9a":{
      "scriptId":"u64"},
    "3974c375e9eb40ef96c496f3bacb734a":{
      "scriptId":"u65"},
    "d2c86faa7b684c8080e6be4655eab356":{
      "scriptId":"u66"},
    "2391967baac84a799ecef0465cd7d4b3":{
      "scriptId":"u67"},
    "f73519e370d34195ae6bbee5ad4d44ca":{
      "scriptId":"u68"},
    "1e26c14b9e3a4a2ca43acecd56f3b925":{
      "scriptId":"u69"}}});