$axure.loadCurrentPage({
  "url":"businese.jsp",
  "generationDate":new Date(1417055440590.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"addae24c7bf7490ab196e860edcf1265",
    "type":"Axure:Page",
    "name":"businese",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7bdfc6ae17c64776ae5ad233eadb2d49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":810,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a28fe1294a8c4fb18139d8fdd2a61772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":810,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"10626e3c8ebc4db0800d75aa5a759c6f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":165},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0e1863a44c6d4e37a7a1db175df2fa91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":172,
              "y":170},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3811392a60c42b1be645a364a67e337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":172,
                  "y":170},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"855ef1bdbe4c494bb263f9fc732970ea",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":166},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Table)",
                      "objectsToFades":[{
                          "objectPath":["73c86c07d25c4142a6b41de02d3fd965"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"73c86c07d25c4142a6b41de02d3fd965",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":false,
          "style":{
            "location":{
              "x":129,
              "y":235},
            "size":{
              "width":620,
              "height":245},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2deabcbb6e93470a9f74ec35976eeecf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f16fc4a46d8b4a5cb122e97b0ff84c0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":103,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u7.png"}},
{
              "id":"ccfc55728c984e68966707ab9ac71a7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c31d3056caf48a2918b23ac72fd5105",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u19.png"}},
{
              "id":"2dbc16a846fd4875955ffc337c6fcbdb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":103,
                  "height":175}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9088759dd881434ea5c21cb44772cc4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":70},
                    "size":{
                      "width":103,
                      "height":175}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u31.png"}},
{
              "id":"178550f39250496d89514765634bf97b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":0},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"09f58d0122354a13a71520e8cac9ff62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u7.png"}},
{
              "id":"7e19c1357ee3479e83f6db0a9e1bfefd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":40},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a525b90273d14effbb37d7c9da492e2f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":40},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u19.png"}},
{
              "id":"542e770e5b9c4215aa5389a52e551a03",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":70},
                "size":{
                  "width":103,
                  "height":175}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c75624a67074c1b967a23ffe02eeab2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":103,
                      "y":70},
                    "size":{
                      "width":103,
                      "height":175}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u31.png"}},
{
              "id":"072c45a7b51147b28378bd984a87086a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":0},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83375496c9cf4d5995e32ab80d8e25d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u7.png"}},
{
              "id":"52b3834317d64ae88f58f4f4dc68aa82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":40},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f82d037bab354251bf3c89998c9a82cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":40},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u19.png"}},
{
              "id":"f5464945114d4dd4a5759f73a5fe118c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":412,
                  "y":70},
                "size":{
                  "width":103,
                  "height":175}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7711c3733a094adf86044894e13e5ee3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":412,
                      "y":70},
                    "size":{
                      "width":103,
                      "height":175}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u31.png"}},
{
              "id":"12149d5a4f2549a5bdaf450a2e80fc71",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":515,
                  "y":0},
                "size":{
                  "width":105,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6e64de2cc0945b791b80888eca3ba63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":515,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u17.png"}},
{
              "id":"8a460c701acb43abaf7ecbd3bcdfb41d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":515,
                  "y":40},
                "size":{
                  "width":105,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce81e9270f7b4d598cb90b614e8f2f25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":515,
                      "y":40},
                    "size":{
                      "width":105,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u29.png"}},
{
              "id":"3742f0da81d844c9924806159faf6606",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":515,
                  "y":70},
                "size":{
                  "width":105,
                  "height":175}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb3f655a679f4856a274521906999d48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":515,
                      "y":70},
                    "size":{
                      "width":105,
                      "height":175}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u41.png"}},
{
              "id":"00b9b6cf913745ac989eed4a4f70ec0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":0},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8767564c37c4670ad6b95c7ce01ea48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u7.png"}},
{
              "id":"c69d9785f85a4f0ab8315acac318add5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":40},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"488933d237fd45b591bc1cf8b7f88944",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":40},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u19.png"}},
{
              "id":"0ca433b80d6c4698aaf5f8df11f2b702",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":70},
                "size":{
                  "width":103,
                  "height":175}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec3eacc5e3724352aca7b30e4b682fec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":70},
                    "size":{
                      "width":103,
                      "height":175}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u31.png"}},
{
              "id":"54e7e701c99e4807a4fbca9f2341c798",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":0},
                "size":{
                  "width":103,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c4695c591524f9d9dc489ace19aced3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":0},
                    "size":{
                      "width":103,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u7.png"}},
{
              "id":"bc7efabcac784617b4edb6876dbf0e22",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":40},
                "size":{
                  "width":103,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a48b48cb0a7541f98a82b2ee60a0dbb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":40},
                    "size":{
                      "width":103,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u19.png"}},
{
              "id":"91675f43cfcc4f86bb16c2a85015dcfd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":309,
                  "y":70},
                "size":{
                  "width":103,
                  "height":175}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"903506498653446fac867fe5e0473ed8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":309,
                      "y":70},
                    "size":{
                      "width":103,
                      "height":175}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/businese/u31.png"}}]},
{
          "id":"83cbf32fb42a42c28a7f62f29dcb0faf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":65,
              "y":79},
            "size":{
              "width":175,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c652e6e06c2475f8dfd8515741de926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":65,
                  "y":79},
                "size":{
                  "width":175,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"817e00685e9f49239a7082437fad45ad",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":250,
              "y":70},
            "size":{
              "width":520,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e8b5a44f1e407a9a336fdd2f4433d3",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"391ec9faa8f74c28a9dbe0e8e8f332c2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"133c124cee834851ba0d1091178ea11d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"51da55d86fe942fd895e905042a02729",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a1b1b9e9c0f47e88d448abbcff68509",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":390,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"67a4ba7f089d497ebfd5058054293bb1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15fe7bb046e84b8cb4adb1d9f0b45323",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open index in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"index.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"ecfe04869cff49ef9cf69d2502c524fc",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ad7a64f636e401ea5410fd9f06c4cdd",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open customer in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"customer.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}}]},
{
              "id":"00eedc0fbe5142c1aee2b51e37bf4181",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":50},
                "size":{
                  "width":130,
                  "height":142},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59d3c2ddbf8b4124af602dd5be79bcea",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c43e9c9f9ec4802b3e85d74b1a84216",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5e4ac9fa583f4904907cc18ff199341f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open payment in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"payment.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"5becdf1c35354b30a1c5dd63eee2712b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7ba17b54ddb544b0a6685b8b81f311e2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open inventory in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"inventory.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"166cb0cea16b4a519ba282a6a5e272b9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":130,
                          "height":50},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2da893953fa04066b326ba7cb129a1b4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":130,
                              "height":50},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open newcustomer in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"newcustomer.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u14.png"}}]}],
              "parentCellId":"391ec9faa8f74c28a9dbe0e8e8f332c2"},
{
              "id":"e46c21eb6c284b049efe8c76bdd0ff21",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":50},
                "size":{
                  "width":131,
                  "height":171},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"034dc8d25a5545ddb41bef124e571e48",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":131,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab079798113e4680bcdf712665670abb",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":131,
                          "height":41},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"561f8feaa73a4d369ddb1851c438dade",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":131,
                              "height":41},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open profit in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"profit.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u26.png"}},
{
                      "id":"022f1b1530b34b039eafda7302d2f4c1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":131,
                          "height":38},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b2359fb08a3c45b2980c539b597b07c6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":41},
                            "size":{
                              "width":131,
                              "height":38},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open top products in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"top_products.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u28.png"}},
{
                      "id":"c383bdc6ee794f8c953ec52bd458a279",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e7ab6954aab64127a40b325a9839b3c3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":79},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open comparison in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"comparison.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u30.png"}},
{
                      "id":"0d55ada274164649b1e2ba29e0ffb1f7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3b30b137b0f241ca8c386324ecfec1d8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":125},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open businese in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"businese.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u32.png"}}]}],
              "parentCellId":"51da55d86fe942fd895e905042a02729"}]}]}},
  "masters":{
},
  "objectPaths":{
    "7bdfc6ae17c64776ae5ad233eadb2d49":{
      "scriptId":"u0"},
    "a28fe1294a8c4fb18139d8fdd2a61772":{
      "scriptId":"u1"},
    "10626e3c8ebc4db0800d75aa5a759c6f":{
      "scriptId":"u2"},
    "0e1863a44c6d4e37a7a1db175df2fa91":{
      "scriptId":"u3"},
    "f3811392a60c42b1be645a364a67e337":{
      "scriptId":"u4"},
    "855ef1bdbe4c494bb263f9fc732970ea":{
      "scriptId":"u5"},
    "73c86c07d25c4142a6b41de02d3fd965":{
      "scriptId":"u6"},
    "2deabcbb6e93470a9f74ec35976eeecf":{
      "scriptId":"u7"},
    "f16fc4a46d8b4a5cb122e97b0ff84c0f":{
      "scriptId":"u8"},
    "178550f39250496d89514765634bf97b":{
      "scriptId":"u9"},
    "09f58d0122354a13a71520e8cac9ff62":{
      "scriptId":"u10"},
    "00b9b6cf913745ac989eed4a4f70ec0e":{
      "scriptId":"u11"},
    "c8767564c37c4670ad6b95c7ce01ea48":{
      "scriptId":"u12"},
    "54e7e701c99e4807a4fbca9f2341c798":{
      "scriptId":"u13"},
    "8c4695c591524f9d9dc489ace19aced3":{
      "scriptId":"u14"},
    "072c45a7b51147b28378bd984a87086a":{
      "scriptId":"u15"},
    "83375496c9cf4d5995e32ab80d8e25d0":{
      "scriptId":"u16"},
    "12149d5a4f2549a5bdaf450a2e80fc71":{
      "scriptId":"u17"},
    "a6e64de2cc0945b791b80888eca3ba63":{
      "scriptId":"u18"},
    "ccfc55728c984e68966707ab9ac71a7b":{
      "scriptId":"u19"},
    "0c31d3056caf48a2918b23ac72fd5105":{
      "scriptId":"u20"},
    "7e19c1357ee3479e83f6db0a9e1bfefd":{
      "scriptId":"u21"},
    "a525b90273d14effbb37d7c9da492e2f":{
      "scriptId":"u22"},
    "c69d9785f85a4f0ab8315acac318add5":{
      "scriptId":"u23"},
    "488933d237fd45b591bc1cf8b7f88944":{
      "scriptId":"u24"},
    "bc7efabcac784617b4edb6876dbf0e22":{
      "scriptId":"u25"},
    "a48b48cb0a7541f98a82b2ee60a0dbb1":{
      "scriptId":"u26"},
    "52b3834317d64ae88f58f4f4dc68aa82":{
      "scriptId":"u27"},
    "f82d037bab354251bf3c89998c9a82cb":{
      "scriptId":"u28"},
    "8a460c701acb43abaf7ecbd3bcdfb41d":{
      "scriptId":"u29"},
    "ce81e9270f7b4d598cb90b614e8f2f25":{
      "scriptId":"u30"},
    "2dbc16a846fd4875955ffc337c6fcbdb":{
      "scriptId":"u31"},
    "9088759dd881434ea5c21cb44772cc4f":{
      "scriptId":"u32"},
    "542e770e5b9c4215aa5389a52e551a03":{
      "scriptId":"u33"},
    "7c75624a67074c1b967a23ffe02eeab2":{
      "scriptId":"u34"},
    "0ca433b80d6c4698aaf5f8df11f2b702":{
      "scriptId":"u35"},
    "ec3eacc5e3724352aca7b30e4b682fec":{
      "scriptId":"u36"},
    "91675f43cfcc4f86bb16c2a85015dcfd":{
      "scriptId":"u37"},
    "903506498653446fac867fe5e0473ed8":{
      "scriptId":"u38"},
    "f5464945114d4dd4a5759f73a5fe118c":{
      "scriptId":"u39"},
    "7711c3733a094adf86044894e13e5ee3":{
      "scriptId":"u40"},
    "3742f0da81d844c9924806159faf6606":{
      "scriptId":"u41"},
    "eb3f655a679f4856a274521906999d48":{
      "scriptId":"u42"},
    "83cbf32fb42a42c28a7f62f29dcb0faf":{
      "scriptId":"u43"},
    "5c652e6e06c2475f8dfd8515741de926":{
      "scriptId":"u44"},
    "817e00685e9f49239a7082437fad45ad":{
      "scriptId":"u45"},
    "d4e8b5a44f1e407a9a336fdd2f4433d3":{
      "scriptId":"u46"},
    "67a4ba7f089d497ebfd5058054293bb1":{
      "scriptId":"u47"},
    "15fe7bb046e84b8cb4adb1d9f0b45323":{
      "scriptId":"u48"},
    "ecfe04869cff49ef9cf69d2502c524fc":{
      "scriptId":"u49"},
    "5ad7a64f636e401ea5410fd9f06c4cdd":{
      "scriptId":"u50"},
    "391ec9faa8f74c28a9dbe0e8e8f332c2":{
      "scriptId":"u51"},
    "133c124cee834851ba0d1091178ea11d":{
      "scriptId":"u52"},
    "51da55d86fe942fd895e905042a02729":{
      "scriptId":"u53"},
    "0a1b1b9e9c0f47e88d448abbcff68509":{
      "scriptId":"u54"},
    "00eedc0fbe5142c1aee2b51e37bf4181":{
      "scriptId":"u55"},
    "59d3c2ddbf8b4124af602dd5be79bcea":{
      "scriptId":"u56"},
    "7c43e9c9f9ec4802b3e85d74b1a84216":{
      "scriptId":"u57"},
    "5e4ac9fa583f4904907cc18ff199341f":{
      "scriptId":"u58"},
    "5becdf1c35354b30a1c5dd63eee2712b":{
      "scriptId":"u59"},
    "7ba17b54ddb544b0a6685b8b81f311e2":{
      "scriptId":"u60"},
    "166cb0cea16b4a519ba282a6a5e272b9":{
      "scriptId":"u61"},
    "2da893953fa04066b326ba7cb129a1b4":{
      "scriptId":"u62"},
    "e46c21eb6c284b049efe8c76bdd0ff21":{
      "scriptId":"u63"},
    "034dc8d25a5545ddb41bef124e571e48":{
      "scriptId":"u64"},
    "ab079798113e4680bcdf712665670abb":{
      "scriptId":"u65"},
    "561f8feaa73a4d369ddb1851c438dade":{
      "scriptId":"u66"},
    "022f1b1530b34b039eafda7302d2f4c1":{
      "scriptId":"u67"},
    "b2359fb08a3c45b2980c539b597b07c6":{
      "scriptId":"u68"},
    "c383bdc6ee794f8c953ec52bd458a279":{
      "scriptId":"u69"},
    "e7ab6954aab64127a40b325a9839b3c3":{
      "scriptId":"u70"},
    "0d55ada274164649b1e2ba29e0ffb1f7":{
      "scriptId":"u71"},
    "3b30b137b0f241ca8c386324ecfec1d8":{
      "scriptId":"u72"}}});