.jsp$axure.loadCurrentPage({
  "url":"inventory.jsp",
  "generationDate":new Date(1417055438791.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a0ff2fccea12430d9737be728385cc2b",
    "type":"Axure:Page",
    "name":"inventory",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e2314bd79be414182ffd1a387f0b12a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":31},
            "size":{
              "width":810,
              "height":569}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fee20c83a9f041fba41ee5350f5aa6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":31},
                "size":{
                  "width":810,
                  "height":569}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory/u0.png"}},
{
          "id":"7db70915b2834e469ddbce66fb39b569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":190,
              "y":230},
            "size":{
              "width":500,
              "height":300},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"928321eb80484ca4aa13b06bbf619033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":190,
                  "y":230},
                "size":{
                  "width":500,
                  "height":300},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory/u2.png"}},
{
          "id":"5066e691bcb64ad59210f5080530fb46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":261,
              "y":279},
            "size":{
              "width":48,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"796e7d120e534fc8955be20c00f52f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":261,
                  "y":279},
                "size":{
                  "width":48,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99750d8cf03d4d1c917ce7044ad1c51e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":261,
              "y":324},
            "size":{
              "width":70,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"394474a91bd44ce09465c07871405f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":261,
                  "y":324},
                "size":{
                  "width":70,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a6041629cfc4bb1b4fd7e2d4b8ad028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":262,
              "y":367},
            "size":{
              "width":42,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61982fb38330434489d031a63e253ab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":262,
                  "y":367},
                "size":{
                  "width":42,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c565167ce304d9ea4d3f20c0691420e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":261,
              "y":412},
            "size":{
              "width":97,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c66c0e48f794f45b312d50f17915427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":261,
                  "y":412},
                "size":{
                  "width":97,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ced7afeeeb8f4d2986057a8e33298e8a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":400,
              "y":279},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"3ca8c90d479748f38313023767ac5517",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":400,
              "y":319},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"bc31c73fcbb44df28eec96800b88f1c0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":400,
              "y":365},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"59391d7a694744cb877cff0fb8999a5b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":400,
              "y":406},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"d2405699e88046a38c2c68ce6188f22b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":426,
              "y":461},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"89c77d26bedd4d2ab68a671707733d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":190,
              "y":202},
            "size":{
              "width":500,
              "height":356},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6248614f37b14b0c8804d941f34e903d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":190,
                  "y":202},
                "size":{
                  "width":500,
                  "height":356},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory/u17.png"}},
{
          "id":"0b2457bd1fc542ce8698515befb4f381",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":340,
              "y":232},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"dcaaa3ec75aa43cf9eb7228011085bf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":241,
              "y":237},
            "size":{
              "width":80,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8414c6dae6ca462bba475eee1b4b403e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":241,
                  "y":237},
                "size":{
                  "width":80,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b7ac8825ebb491f90310053141d4bd0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":570,
              "y":232},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Text Field),<br>(HTML Button),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape)",
                      "objectsToFades":[{
                          "objectPath":["eebda7ef2ccc4f78b2af8fa90a52a69c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["99287fac6b2e4c8ba551278f31e7ebc2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a8d118f8e9294b0eaf44e42a474d5f52"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aa3455202ad441b8934e0413914afa6b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4242ddd0ce7c46d180d8cb38277302dd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["946a327744d04dbeb9e60a9c546bb31e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f345ac3d393e4b01a79fa750ac6f7289"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["abfafc90fe844573941c30e343e878e5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"abfafc90fe844573941c30e343e878e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":241,
              "y":286},
            "size":{
              "width":389,
              "height":209},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac91df66a9b4a6f847744f14cbc26ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":241,
                  "y":286},
                "size":{
                  "width":389,
                  "height":209},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/inventory/u23.png"}},
{
          "id":"f345ac3d393e4b01a79fa750ac6f7289",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":278,
              "y":306},
            "size":{
              "width":80,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09419614de594bc5bdbaf849856a107c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":278,
                  "y":306},
                "size":{
                  "width":80,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"946a327744d04dbeb9e60a9c546bb31e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":278,
              "y":342},
            "size":{
              "width":48,
              "height":15},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d52f27077e774cdcb66aab778e9d68e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":278,
                  "y":342},
                "size":{
                  "width":48,
                  "height":15},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4242ddd0ce7c46d180d8cb38277302dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":278,
              "y":377},
            "size":{
              "width":70,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac3a47c356f4a8ba0df788c4c65d94b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":278,
                  "y":377},
                "size":{
                  "width":70,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa3455202ad441b8934e0413914afa6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":278,
              "y":416},
            "size":{
              "width":42,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fecedad80ee24d1fbe74e320117cc078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":278,
                  "y":416},
                "size":{
                  "width":42,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8d118f8e9294b0eaf44e42a474d5f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":278,
              "y":455},
            "size":{
              "width":97,
              "height":18},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b362317dc674ad6aa18f69ee08f7677",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":278,
                  "y":455},
                "size":{
                  "width":97,
                  "height":18},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eebda7ef2ccc4f78b2af8fa90a52a69c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "location":{
              "x":387,
              "y":374},
            "size":{
              "width":200,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"99287fac6b2e4c8ba551278f31e7ebc2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":386,
              "y":505},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"d7efd720a8b847ba845693a44017ee4a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":258,
              "y":174},
            "size":{
              "width":144,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0ea5b3ddce43ed862ee130e6455b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":258,
                  "y":174},
                "size":{
                  "width":144,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"Case 1<br> (If is selected of This equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(HTML Button),<br>Hide (Shape),<br>(Text Field),<br>(HTML Button),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(HTML Button),<br>(Shape)",
                      "objectsToFades":[{
                          "objectPath":["7db70915b2834e469ddbce66fb39b569"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5066e691bcb64ad59210f5080530fb46"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5a6041629cfc4bb1b4fd7e2d4b8ad028"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["99750d8cf03d4d1c917ce7044ad1c51e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0c565167ce304d9ea4d3f20c0691420e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ced7afeeeb8f4d2986057a8e33298e8a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3ca8c90d479748f38313023767ac5517"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["59391d7a694744cb877cff0fb8999a5b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["bc31c73fcbb44df28eec96800b88f1c0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d2405699e88046a38c2c68ce6188f22b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["89c77d26bedd4d2ab68a671707733d84"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0b2457bd1fc542ce8698515befb4f381"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["99287fac6b2e4c8ba551278f31e7ebc2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["eebda7ef2ccc4f78b2af8fa90a52a69c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a8d118f8e9294b0eaf44e42a474d5f52"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aa3455202ad441b8934e0413914afa6b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4242ddd0ce7c46d180d8cb38277302dd"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["946a327744d04dbeb9e60a9c546bb31e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f345ac3d393e4b01a79fa750ac6f7289"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["abfafc90fe844573941c30e343e878e5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8b7ac8825ebb491f90310053141d4bd0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["dcaaa3ec75aa43cf9eb7228011085bf5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"8fb34e3e0aec4b85ac20da0054e671b2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":483,
              "y":174},
            "size":{
              "width":100,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cbdcea466e74d15a6d18840a5196ed4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":483,
                  "y":174},
                "size":{
                  "width":100,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"Case 1<br> (If is selected of This equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (HTML Button),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(HTML Button),<br>(Shape),<br>(Text Field),<br>(Shape),<br>Hide (HTML Button),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape),<br>(Shape)",
                      "objectsToFades":[{
                          "objectPath":["99287fac6b2e4c8ba551278f31e7ebc2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["eebda7ef2ccc4f78b2af8fa90a52a69c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a8d118f8e9294b0eaf44e42a474d5f52"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aa3455202ad441b8934e0413914afa6b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["946a327744d04dbeb9e60a9c546bb31e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4242ddd0ce7c46d180d8cb38277302dd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f345ac3d393e4b01a79fa750ac6f7289"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["abfafc90fe844573941c30e343e878e5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8b7ac8825ebb491f90310053141d4bd0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["dcaaa3ec75aa43cf9eb7228011085bf5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0b2457bd1fc542ce8698515befb4f381"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["89c77d26bedd4d2ab68a671707733d84"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d2405699e88046a38c2c68ce6188f22b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["59391d7a694744cb877cff0fb8999a5b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["bc31c73fcbb44df28eec96800b88f1c0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3ca8c90d479748f38313023767ac5517"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ced7afeeeb8f4d2986057a8e33298e8a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0c565167ce304d9ea4d3f20c0691420e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5a6041629cfc4bb1b4fd7e2d4b8ad028"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["99750d8cf03d4d1c917ce7044ad1c51e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7db70915b2834e469ddbce66fb39b569"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5066e691bcb64ad59210f5080530fb46"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"397a04a5c66c4769b9d14e480245f072",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":65,
              "y":79},
            "size":{
              "width":175,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faae1263733846f2b079a276987c3537",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":65,
                  "y":79},
                "size":{
                  "width":175,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6146fefb7a224abb8e731d41687fd8f3",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":250,
              "y":70},
            "size":{
              "width":520,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af4450ecb6874d4ea40490ed74df9e0a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3704854da675403d98600fdf5f01b4f6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9df6513ee5b54febb02adf0d7680510f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"c15d780533db498ca2cc8b75a00ba167",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"138fd55c12814102bf64320d0dc99499",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":390,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"a13990595d634ee4b93b1a2f20bb8505",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"682f60a8f0ec4188a045ca625d0b5c43",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open index in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"index.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"0fa6ce6cccd44f46b53b8196e8f2bb2a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"948923f9ba1846aeab5f39afcb965302",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open customer in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"customer.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}}]},
{
              "id":"3049e45bc31347a8acc25df593058c91",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":50},
                "size":{
                  "width":130,
                  "height":142},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31a62dceff8447b9a94af81ec60b8dd3",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce5e703410aa4374a0021cbd2d072277",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"48ce1acc520f43c4b4083ff377cfdd44",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open payment in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"payment.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"065470176c2542b589340837a9fc43d7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8377e26674b64fbc8324044ea17bb608",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open inventory in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"inventory.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"a83ccf098b2e43be87da80d6ff6a35f4",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":130,
                          "height":50},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c4b3f306e3e64dd6a19036534aeb4043",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":130,
                              "height":50},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open newcustomer in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"newcustomer.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u14.png"}}]}],
              "parentCellId":"3704854da675403d98600fdf5f01b4f6"},
{
              "id":"a3947569d55b4710a2bfdb58b4840931",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":50},
                "size":{
                  "width":131,
                  "height":171},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3024c9eaa3554830abf18f0fbc793c27",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":131,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6292deaed6548a1811a0ce0e6dad719",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":131,
                          "height":41},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d0672f1a3c14418ca1d2bace17ffa04f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":131,
                              "height":41},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open profit in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"profit.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u26.png"}},
{
                      "id":"2d71575628d64965aa57292e3eb40777",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":131,
                          "height":38},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2dec5b353f244413b20805f7db33ebca",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":41},
                            "size":{
                              "width":131,
                              "height":38},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open top products in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"top_products.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u28.png"}},
{
                      "id":"b74e891ad4134b7aaac3f9ee318b73a0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3eae5dad562349beb300ebc1a55b46d5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":79},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open comparison in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"comparison.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u30.png"}},
{
                      "id":"b238ddea34e24023ae1cd7df5dabeed1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"49ae583b550e40dab7cedb2f7048bd7b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":125},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open businese in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"businese.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u32.png"}}]}],
              "parentCellId":"c15d780533db498ca2cc8b75a00ba167"}]},
{
          "id":"c43fed9a09684c33956db90cfd32f967",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":false,
          "style":{
            "location":{
              "x":388,
              "y":449},
            "size":{
              "width":200,
              "height":28},
            "visible":false},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "1e2314bd79be414182ffd1a387f0b12a":{
      "scriptId":"u0"},
    "fee20c83a9f041fba41ee5350f5aa6b3":{
      "scriptId":"u1"},
    "7db70915b2834e469ddbce66fb39b569":{
      "scriptId":"u2"},
    "928321eb80484ca4aa13b06bbf619033":{
      "scriptId":"u3"},
    "5066e691bcb64ad59210f5080530fb46":{
      "scriptId":"u4"},
    "796e7d120e534fc8955be20c00f52f02":{
      "scriptId":"u5"},
    "99750d8cf03d4d1c917ce7044ad1c51e":{
      "scriptId":"u6"},
    "394474a91bd44ce09465c07871405f99":{
      "scriptId":"u7"},
    "5a6041629cfc4bb1b4fd7e2d4b8ad028":{
      "scriptId":"u8"},
    "61982fb38330434489d031a63e253ab9":{
      "scriptId":"u9"},
    "0c565167ce304d9ea4d3f20c0691420e":{
      "scriptId":"u10"},
    "8c66c0e48f794f45b312d50f17915427":{
      "scriptId":"u11"},
    "ced7afeeeb8f4d2986057a8e33298e8a":{
      "scriptId":"u12"},
    "3ca8c90d479748f38313023767ac5517":{
      "scriptId":"u13"},
    "bc31c73fcbb44df28eec96800b88f1c0":{
      "scriptId":"u14"},
    "59391d7a694744cb877cff0fb8999a5b":{
      "scriptId":"u15"},
    "d2405699e88046a38c2c68ce6188f22b":{
      "scriptId":"u16"},
    "89c77d26bedd4d2ab68a671707733d84":{
      "scriptId":"u17"},
    "6248614f37b14b0c8804d941f34e903d":{
      "scriptId":"u18"},
    "0b2457bd1fc542ce8698515befb4f381":{
      "scriptId":"u19"},
    "dcaaa3ec75aa43cf9eb7228011085bf5":{
      "scriptId":"u20"},
    "8414c6dae6ca462bba475eee1b4b403e":{
      "scriptId":"u21"},
    "8b7ac8825ebb491f90310053141d4bd0":{
      "scriptId":"u22"},
    "abfafc90fe844573941c30e343e878e5":{
      "scriptId":"u23"},
    "2ac91df66a9b4a6f847744f14cbc26ca":{
      "scriptId":"u24"},
    "f345ac3d393e4b01a79fa750ac6f7289":{
      "scriptId":"u25"},
    "09419614de594bc5bdbaf849856a107c":{
      "scriptId":"u26"},
    "946a327744d04dbeb9e60a9c546bb31e":{
      "scriptId":"u27"},
    "d52f27077e774cdcb66aab778e9d68e6":{
      "scriptId":"u28"},
    "4242ddd0ce7c46d180d8cb38277302dd":{
      "scriptId":"u29"},
    "9ac3a47c356f4a8ba0df788c4c65d94b":{
      "scriptId":"u30"},
    "aa3455202ad441b8934e0413914afa6b":{
      "scriptId":"u31"},
    "fecedad80ee24d1fbe74e320117cc078":{
      "scriptId":"u32"},
    "a8d118f8e9294b0eaf44e42a474d5f52":{
      "scriptId":"u33"},
    "3b362317dc674ad6aa18f69ee08f7677":{
      "scriptId":"u34"},
    "eebda7ef2ccc4f78b2af8fa90a52a69c":{
      "scriptId":"u35"},
    "99287fac6b2e4c8ba551278f31e7ebc2":{
      "scriptId":"u36"},
    "d7efd720a8b847ba845693a44017ee4a":{
      "scriptId":"u37"},
    "ce0ea5b3ddce43ed862ee130e6455b3a":{
      "scriptId":"u38"},
    "8fb34e3e0aec4b85ac20da0054e671b2":{
      "scriptId":"u39"},
    "3cbdcea466e74d15a6d18840a5196ed4":{
      "scriptId":"u40"},
    "397a04a5c66c4769b9d14e480245f072":{
      "scriptId":"u41"},
    "faae1263733846f2b079a276987c3537":{
      "scriptId":"u42"},
    "6146fefb7a224abb8e731d41687fd8f3":{
      "scriptId":"u43"},
    "af4450ecb6874d4ea40490ed74df9e0a":{
      "scriptId":"u44"},
    "a13990595d634ee4b93b1a2f20bb8505":{
      "scriptId":"u45"},
    "682f60a8f0ec4188a045ca625d0b5c43":{
      "scriptId":"u46"},
    "0fa6ce6cccd44f46b53b8196e8f2bb2a":{
      "scriptId":"u47"},
    "948923f9ba1846aeab5f39afcb965302":{
      "scriptId":"u48"},
    "3704854da675403d98600fdf5f01b4f6":{
      "scriptId":"u49"},
    "9df6513ee5b54febb02adf0d7680510f":{
      "scriptId":"u50"},
    "c15d780533db498ca2cc8b75a00ba167":{
      "scriptId":"u51"},
    "138fd55c12814102bf64320d0dc99499":{
      "scriptId":"u52"},
    "3049e45bc31347a8acc25df593058c91":{
      "scriptId":"u53"},
    "31a62dceff8447b9a94af81ec60b8dd3":{
      "scriptId":"u54"},
    "ce5e703410aa4374a0021cbd2d072277":{
      "scriptId":"u55"},
    "48ce1acc520f43c4b4083ff377cfdd44":{
      "scriptId":"u56"},
    "065470176c2542b589340837a9fc43d7":{
      "scriptId":"u57"},
    "8377e26674b64fbc8324044ea17bb608":{
      "scriptId":"u58"},
    "a83ccf098b2e43be87da80d6ff6a35f4":{
      "scriptId":"u59"},
    "c4b3f306e3e64dd6a19036534aeb4043":{
      "scriptId":"u60"},
    "a3947569d55b4710a2bfdb58b4840931":{
      "scriptId":"u61"},
    "3024c9eaa3554830abf18f0fbc793c27":{
      "scriptId":"u62"},
    "a6292deaed6548a1811a0ce0e6dad719":{
      "scriptId":"u63"},
    "d0672f1a3c14418ca1d2bace17ffa04f":{
      "scriptId":"u64"},
    "2d71575628d64965aa57292e3eb40777":{
      "scriptId":"u65"},
    "2dec5b353f244413b20805f7db33ebca":{
      "scriptId":"u66"},
    "b74e891ad4134b7aaac3f9ee318b73a0":{
      "scriptId":"u67"},
    "3eae5dad562349beb300ebc1a55b46d5":{
      "scriptId":"u68"},
    "b238ddea34e24023ae1cd7df5dabeed1":{
      "scriptId":"u69"},
    "49ae583b550e40dab7cedb2f7048bd7b":{
      "scriptId":"u70"},
    "c43fed9a09684c33956db90cfd32f967":{
      "scriptId":"u71"}}});