$axure.loadCurrentPage({
  "url":"comparison.jsp",
  "generationDate":new Date(1417055440342.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ee6a65e26784063ad4f04a9d354980d",
    "type":"Axure:Page",
    "name":"comparison",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f851b5129a249e5a39d37c10b213a61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":810,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ee227956ba4f6f8a0de88a68c25471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":810,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"18efeb802a8a4d279a0b566c620a40fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":168},
            "size":{
              "width":640,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04a1f1654b2046e3919a1fe409b2a600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":168},
                "size":{
                  "width":640,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/comparison/u2.png"}},
{
          "id":"7b86b8892cc24639a61a96ef168d4016",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":192},
            "size":{
              "width":229,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da13e77a60f43b88c10dd195a749753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":192},
                "size":{
                  "width":229,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92f7778a36a4456bb444c939f239020b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":250},
            "size":{
              "width":200,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b07469b118af4c79bf13f0a709cb0478",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae6dbf70e4474d74b0d388e0fcfab51c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u7.png"}},
{
              "id":"9dcc3cf2b9ff465ba9e6323b02a81446",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29b3844052794bc49d4586f578805e7d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u11.png"}},
{
              "id":"fb0da1fe807643b7bcf8eb1bf4ba4482",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":100,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4784179a7bdf4ac39e9dbc1e5d1a732a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":79},
                    "size":{
                      "width":100,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u15.png"}},
{
              "id":"d7c4c30af12a45eeb35998486406c33b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5777a8b89f524efdb58fa0a7a15476f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u9.png"}},
{
              "id":"ec2ec751756548c9a429d27e739d6ab8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48edbf58024d43548207755e70a24068",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u13.png"}},
{
              "id":"adf1ca61ac6941a58abb87ea6b0ff44a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":79},
                "size":{
                  "width":100,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1386e78b15fd449bb7973db6bd552bca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":79},
                    "size":{
                      "width":100,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u17.png"}},
{
              "id":"a53e3079d3bd401a91fe05c31fb69efc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":127},
                "size":{
                  "width":100,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8c7b939db5d444088d16c7b2a09b692",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":127},
                    "size":{
                      "width":100,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u19.png"}},
{
              "id":"370ac4b442674408ae05ddddfb10b379",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":127},
                "size":{
                  "width":100,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e14d5f60c7854c5abe7a4881a66a4b4d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":127},
                    "size":{
                      "width":100,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u21.png"}},
{
              "id":"5942f0d1572b4a1b9cff9551eb6a5363",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":172},
                "size":{
                  "width":100,
                  "height":51}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a54273cdb344d338d533eed44b64883",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":172},
                    "size":{
                      "width":100,
                      "height":51}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u23.png"}},
{
              "id":"d6f0242f4c424b829c7383812411c67f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":172},
                "size":{
                  "width":100,
                  "height":51}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3fb237c9dbe4ab086e59aa8574b0422",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":172},
                    "size":{
                      "width":100,
                      "height":51}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u25.png"}}]},
{
          "id":"07f5a04dfd3f4352a260efd4640ca9c3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":250},
            "size":{
              "width":200,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ded0cdf721a244488fc4ef0329142550",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95296de6cfcd420198597507887a8365",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u7.png"}},
{
              "id":"fbec1c4b6fc74ab28edff3b31ee3258a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa2f5e4dc7bf433b9518f3fbf5b4de38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u11.png"}},
{
              "id":"13be2563cdd842a7be5c39e603e534fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":79},
                "size":{
                  "width":100,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3aa982d98c7845c0b6aae0b3ed949509",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":79},
                    "size":{
                      "width":100,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u15.png"}},
{
              "id":"03cf0877b0804dcbbd15859cbcb0a7cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4637e72bdc21459fbdbc1adc7645cb61",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/top_products/u9.png"}},
{
              "id":"f563956d776640b79a0d83aaa0591f73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c24cf9be74984d0f9269b0ee2c7dce90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u13.png"}},
{
              "id":"55572b1443b04c43a861502f246f7e89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":79},
                "size":{
                  "width":100,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b05639ad8a9042aca99dc1f744486a49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":79},
                    "size":{
                      "width":100,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u17.png"}},
{
              "id":"253ebcc054a249d6a78ee60563452a52",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":127},
                "size":{
                  "width":100,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56e10d500d994609af8e6c75d228389b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":127},
                    "size":{
                      "width":100,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u19.png"}},
{
              "id":"4ebdeb8cf2d04f468789ace4b87a1b2f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":127},
                "size":{
                  "width":100,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6eb31b0c1d09443a90c4b5895983e1ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":127},
                    "size":{
                      "width":100,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u21.png"}},
{
              "id":"885ab70f781042b589f42a1654611583",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":172},
                "size":{
                  "width":100,
                  "height":51}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0bc219121f0344a9a2aeddc14d4a88cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":172},
                    "size":{
                      "width":100,
                      "height":51}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u23.png"}},
{
              "id":"d1151dd0350c41feb2d03703e15c2534",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":172},
                "size":{
                  "width":100,
                  "height":51}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e43d68b4bb142b7b656c6feb1d5a432",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":172},
                    "size":{
                      "width":100,
                      "height":51}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comparison/u25.png"}}]},
{
          "id":"a06ddca7262847fc90d9a65ad836c31f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":65,
              "y":79},
            "size":{
              "width":175,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f30f8753c40844c492a70307a9f11bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":65,
                  "y":79},
                "size":{
                  "width":175,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44b6a8014b8c4888906812068c9200bd",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":250,
              "y":70},
            "size":{
              "width":520,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0030b352ce584143a42efa64d8cccde7",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38b3dcfaf62c43059bc0cc6fefc0a571",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"836ed67a30ed4fdb9ac351ad76499be3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"7de8ea2ed8354e11ba2d52fcd8f03846",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf835458044244bb81d5e2c734500a9d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":390,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"389187a89cd14dbfbf4d0f6566bad3ad",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b466076547184296a001b051ff78a567",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open index in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"index.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"8b472f641bd94b55a5889c55d51017e1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b82335e12084e7089fb459aa0a0a235",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open customer in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"customer.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}}]},
{
              "id":"204b519bd1d44da3b7ddbf06e4beb928",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":50},
                "size":{
                  "width":130,
                  "height":142},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e781a1b01a564bf6a0d65bdc42649b81",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97dc1f2f475f4a21921d16c114e9e9bc",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5e12c019b9be4bbb946677070bbbfcc0",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open payment in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"payment.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"b5f84e89b9454c9cbf07300a0bb219a3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"45f63ca6ba614cca8fd6e01fa9402c0a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open inventory in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"inventory.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"ba1e908a97fb4411b8b339631792a10b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":130,
                          "height":50},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3d78e270b292403081f6aaa2cc95f614",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":130,
                              "height":50},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open newcustomer in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"newcustomer.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u14.png"}}]}],
              "parentCellId":"38b3dcfaf62c43059bc0cc6fefc0a571"},
{
              "id":"58f1d8ccc9df48ef9dfc5485ac7bdf22",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":50},
                "size":{
                  "width":131,
                  "height":171},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3a6b7c0e68b446db5d4339eb72e0905",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":131,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15a844f9726d42e7bd0d82bda7ece234",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":131,
                          "height":41},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a34c6f1110364b83b84e60a2dc77c5cb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":131,
                              "height":41},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open profit in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"profit.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u26.png"}},
{
                      "id":"243884e28bda41eea5bfe0998d0c0cdf",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":131,
                          "height":38},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e09d4026e56947beb3b5f79e8550f394",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":41},
                            "size":{
                              "width":131,
                              "height":38},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open top products in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"top_products.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u28.png"}},
{
                      "id":"7ec4e971339e453397f112edc127832c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5aeea9dc7fce47d2ba6f8ed03217423d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":79},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open comparison in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"comparison.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u30.png"}},
{
                      "id":"23a813e729da4b52901358857ce17c38",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7ece7a2b3a95413f843734216e75fe55",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":125},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open businese in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"businese.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u32.png"}}]}],
              "parentCellId":"7de8ea2ed8354e11ba2d52fcd8f03846"}]}]}},
  "masters":{
},
  "objectPaths":{
    "7f851b5129a249e5a39d37c10b213a61":{
      "scriptId":"u0"},
    "09ee227956ba4f6f8a0de88a68c25471":{
      "scriptId":"u1"},
    "18efeb802a8a4d279a0b566c620a40fb":{
      "scriptId":"u2"},
    "04a1f1654b2046e3919a1fe409b2a600":{
      "scriptId":"u3"},
    "7b86b8892cc24639a61a96ef168d4016":{
      "scriptId":"u4"},
    "4da13e77a60f43b88c10dd195a749753":{
      "scriptId":"u5"},
    "92f7778a36a4456bb444c939f239020b":{
      "scriptId":"u6"},
    "b07469b118af4c79bf13f0a709cb0478":{
      "scriptId":"u7"},
    "ae6dbf70e4474d74b0d388e0fcfab51c":{
      "scriptId":"u8"},
    "d7c4c30af12a45eeb35998486406c33b":{
      "scriptId":"u9"},
    "5777a8b89f524efdb58fa0a7a15476f0":{
      "scriptId":"u10"},
    "9dcc3cf2b9ff465ba9e6323b02a81446":{
      "scriptId":"u11"},
    "29b3844052794bc49d4586f578805e7d":{
      "scriptId":"u12"},
    "ec2ec751756548c9a429d27e739d6ab8":{
      "scriptId":"u13"},
    "48edbf58024d43548207755e70a24068":{
      "scriptId":"u14"},
    "fb0da1fe807643b7bcf8eb1bf4ba4482":{
      "scriptId":"u15"},
    "4784179a7bdf4ac39e9dbc1e5d1a732a":{
      "scriptId":"u16"},
    "adf1ca61ac6941a58abb87ea6b0ff44a":{
      "scriptId":"u17"},
    "1386e78b15fd449bb7973db6bd552bca":{
      "scriptId":"u18"},
    "a53e3079d3bd401a91fe05c31fb69efc":{
      "scriptId":"u19"},
    "e8c7b939db5d444088d16c7b2a09b692":{
      "scriptId":"u20"},
    "370ac4b442674408ae05ddddfb10b379":{
      "scriptId":"u21"},
    "e14d5f60c7854c5abe7a4881a66a4b4d":{
      "scriptId":"u22"},
    "5942f0d1572b4a1b9cff9551eb6a5363":{
      "scriptId":"u23"},
    "1a54273cdb344d338d533eed44b64883":{
      "scriptId":"u24"},
    "d6f0242f4c424b829c7383812411c67f":{
      "scriptId":"u25"},
    "e3fb237c9dbe4ab086e59aa8574b0422":{
      "scriptId":"u26"},
    "07f5a04dfd3f4352a260efd4640ca9c3":{
      "scriptId":"u27"},
    "ded0cdf721a244488fc4ef0329142550":{
      "scriptId":"u28"},
    "95296de6cfcd420198597507887a8365":{
      "scriptId":"u29"},
    "03cf0877b0804dcbbd15859cbcb0a7cd":{
      "scriptId":"u30"},
    "4637e72bdc21459fbdbc1adc7645cb61":{
      "scriptId":"u31"},
    "fbec1c4b6fc74ab28edff3b31ee3258a":{
      "scriptId":"u32"},
    "fa2f5e4dc7bf433b9518f3fbf5b4de38":{
      "scriptId":"u33"},
    "f563956d776640b79a0d83aaa0591f73":{
      "scriptId":"u34"},
    "c24cf9be74984d0f9269b0ee2c7dce90":{
      "scriptId":"u35"},
    "13be2563cdd842a7be5c39e603e534fa":{
      "scriptId":"u36"},
    "3aa982d98c7845c0b6aae0b3ed949509":{
      "scriptId":"u37"},
    "55572b1443b04c43a861502f246f7e89":{
      "scriptId":"u38"},
    "b05639ad8a9042aca99dc1f744486a49":{
      "scriptId":"u39"},
    "253ebcc054a249d6a78ee60563452a52":{
      "scriptId":"u40"},
    "56e10d500d994609af8e6c75d228389b":{
      "scriptId":"u41"},
    "4ebdeb8cf2d04f468789ace4b87a1b2f":{
      "scriptId":"u42"},
    "6eb31b0c1d09443a90c4b5895983e1ff":{
      "scriptId":"u43"},
    "885ab70f781042b589f42a1654611583":{
      "scriptId":"u44"},
    "0bc219121f0344a9a2aeddc14d4a88cd":{
      "scriptId":"u45"},
    "d1151dd0350c41feb2d03703e15c2534":{
      "scriptId":"u46"},
    "0e43d68b4bb142b7b656c6feb1d5a432":{
      "scriptId":"u47"},
    "a06ddca7262847fc90d9a65ad836c31f":{
      "scriptId":"u48"},
    "f30f8753c40844c492a70307a9f11bf1":{
      "scriptId":"u49"},
    "44b6a8014b8c4888906812068c9200bd":{
      "scriptId":"u50"},
    "0030b352ce584143a42efa64d8cccde7":{
      "scriptId":"u51"},
    "389187a89cd14dbfbf4d0f6566bad3ad":{
      "scriptId":"u52"},
    "b466076547184296a001b051ff78a567":{
      "scriptId":"u53"},
    "8b472f641bd94b55a5889c55d51017e1":{
      "scriptId":"u54"},
    "1b82335e12084e7089fb459aa0a0a235":{
      "scriptId":"u55"},
    "38b3dcfaf62c43059bc0cc6fefc0a571":{
      "scriptId":"u56"},
    "836ed67a30ed4fdb9ac351ad76499be3":{
      "scriptId":"u57"},
    "7de8ea2ed8354e11ba2d52fcd8f03846":{
      "scriptId":"u58"},
    "bf835458044244bb81d5e2c734500a9d":{
      "scriptId":"u59"},
    "204b519bd1d44da3b7ddbf06e4beb928":{
      "scriptId":"u60"},
    "e781a1b01a564bf6a0d65bdc42649b81":{
      "scriptId":"u61"},
    "97dc1f2f475f4a21921d16c114e9e9bc":{
      "scriptId":"u62"},
    "5e12c019b9be4bbb946677070bbbfcc0":{
      "scriptId":"u63"},
    "b5f84e89b9454c9cbf07300a0bb219a3":{
      "scriptId":"u64"},
    "45f63ca6ba614cca8fd6e01fa9402c0a":{
      "scriptId":"u65"},
    "ba1e908a97fb4411b8b339631792a10b":{
      "scriptId":"u66"},
    "3d78e270b292403081f6aaa2cc95f614":{
      "scriptId":"u67"},
    "58f1d8ccc9df48ef9dfc5485ac7bdf22":{
      "scriptId":"u68"},
    "a3a6b7c0e68b446db5d4339eb72e0905":{
      "scriptId":"u69"},
    "15a844f9726d42e7bd0d82bda7ece234":{
      "scriptId":"u70"},
    "a34c6f1110364b83b84e60a2dc77c5cb":{
      "scriptId":"u71"},
    "243884e28bda41eea5bfe0998d0c0cdf":{
      "scriptId":"u72"},
    "e09d4026e56947beb3b5f79e8550f394":{
      "scriptId":"u73"},
    "7ec4e971339e453397f112edc127832c":{
      "scriptId":"u74"},
    "5aeea9dc7fce47d2ba6f8ed03217423d":{
      "scriptId":"u75"},
    "23a813e729da4b52901358857ce17c38":{
      "scriptId":"u76"},
    "7ece7a2b3a95413f843734216e75fe55":{
      "scriptId":"u77"}}});