.jsp$axure.loadCurrentPage({
  "url":"customer.jsp",
  "generationDate":new Date(1417055438213.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8aa892783ca749dbad1571f10ddc4ca1",
    "type":"Axure:Page",
    "name":"customer",
    "notes":{
},.jsp
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"021a4f6c210d4ed8b58eb6d77da6e99c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":30},
            "size":{
              "width":810,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8443e34bf0054254818947da6f02324d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":30},
                "size":{
                  "width":810,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"9019ed2b6f904be58f5267b87e6784c4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":150},
            "size":{
              "width":330,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8dad415a7e9d43288538dc69ef7bf3e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":100,
              "y":155},
            "size":{
              "width":110,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1768dd40f4b144ad8b2ff40c195e92ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":100,
                  "y":155},
                "size":{
                  "width":110,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc32025c1cc347bea9c5fbb2bd6d1a43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":100,
              "y":207},
            "size":{
              "width":42,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c574147a9d4aabb2805197604f9f95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":100,
                  "y":207},
                "size":{
                  "width":42,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1e3806fff3d4ec7b46f2947aa1c3f56",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":204},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"0.00"},
{
          "id":"8af107abccab45a5bd189abc527f8b40",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":202},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"0.00"},
{
          "id":"386f4eb3596a45ad8ce10e1751a84d0f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":211},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/customer/u9_line.png"}},
{
          "id":"734115138f2340c0965c192befb6b041",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":false,
          "style":{
            "location":{
              "x":119,
              "y":267},
            "size":{
              "width":611,
              "height":250},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c11b6fa49445a89f5d30199598b231",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14ad1d4cf0f346cb83f1955f89a9f6d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u11.png"}},
{
              "id":"39b1b0fc98f943b0971e7ed84e80a0f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6236dc009204288bcae959023ae006a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u11.png"}},
{
              "id":"44c94fd4a2164493aca4890695d4a9f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":153,
                  "height":190}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6797ae510511467ab9d0a0067224f281",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":153,
                      "height":190}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u27.png"}},
{
              "id":"0074b7fe3427435db46f5bf542205bd1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":0},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b359ff0f4f714edbb5caf59ce16c4c2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":153,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u11.png"}},
{
              "id":"53b8a928cb7749ceb6406a9a4995564c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":30},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"47c75a92c1f446edb935b5af9bcf2b81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":153,
                      "y":30},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u11.png"}},
{
              "id":"dfe83ecd58834a87b03880fabe7dc492",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":60},
                "size":{
                  "width":153,
                  "height":190}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"270952f1e2744b07a206afb36cb42369",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":153,
                      "y":60},
                    "size":{
                      "width":153,
                      "height":190}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u27.png"}},
{
              "id":"37b2e47a0d3443c4bfc9336d74ea216a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":0},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99f4b2db0ba446d5affa0df2224a63cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u11.png"}},
{
              "id":"5a926baae1304c108b7380a8781b41b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":30},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f929236679514faeb58aa1d0b22ed8c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":30},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u11.png"}},
{
              "id":"291bf558688447fdba93102be29066e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":306,
                  "y":60},
                "size":{
                  "width":153,
                  "height":190}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e3d2e228a9b457bbe5f42378f96b16d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":306,
                      "y":60},
                    "size":{
                      "width":153,
                      "height":190}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u27.png"}},
{
              "id":"3f211c640e55469385bc48c94fbce78d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":0},
                "size":{
                  "width":152,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"808e053edff04e8e85a86616d08bebcc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":0},
                    "size":{
                      "width":152,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u17.png"}},
{
              "id":"6b0adf9760554b608118bab82c1419aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":30},
                "size":{
                  "width":152,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1ef775180ff49ad8ae3af2ddbd7846e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":30},
                    "size":{
                      "width":152,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u17.png"}},
{
              "id":"3573608c24274f0a9c53db4585793704",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":459,
                  "y":60},
                "size":{
                  "width":152,
                  "height":190}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81015a871e5946e2b31e7166698bacdd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":459,
                      "y":60},
                    "size":{
                      "width":152,
                      "height":190}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/customer/u33.png"}}]},
{
          "id":"b78672a624484898a65c989cb460d29f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":297,
              "y":208},
            "size":{
              "width":129,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19923be73a2e467c974c0b261b3481e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":297,
                  "y":208},
                "size":{
                  "width":129,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b2b74c237f24cc7b86c19e8a8e3e283",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":205},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b6766a0379ee4c58b3ffdd20ffdc7cb1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":203.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Shape),<br>(Text Field),<br>(Shape),<br>(Shape),<br>(Text Field),<br>(Text Field),<br>(Horizontal Line),<br>(Table),<br>(Shape),<br>(Droplist),<br>(HTML Button)",
                      "objectsToFades":[{
                          "objectPath":["021a4f6c210d4ed8b58eb6d77da6e99c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9019ed2b6f904be58f5267b87e6784c4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8dad415a7e9d43288538dc69ef7bf3e9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["dc32025c1cc347bea9c5fbb2bd6d1a43"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d1e3806fff3d4ec7b46f2947aa1c3f56"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8af107abccab45a5bd189abc527f8b40"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["386f4eb3596a45ad8ce10e1751a84d0f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["734115138f2340c0965c192befb6b041"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b78672a624484898a65c989cb460d29f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8b2b74c237f24cc7b86c19e8a8e3e283"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b6766a0379ee4c58b3ffdd20ffdc7cb1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"2b345043e60449cdb8656cc997afa23a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":65,
              "y":79},
            "size":{
              "width":175,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21083065d77b4fcea24240cf77d312f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":65,
                  "y":79},
                "size":{
                  "width":175,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48d5ceeda7884241bfca46483d16a8ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":239},
            "size":{
              "width":701,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3a3ba5be84a4623abd2eaee9e709a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":239},
                "size":{
                  "width":701,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4601a111cae94bd6b0ab8bd8fb126e29",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":250,
              "y":70},
            "size":{
              "width":520,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ee79bd3acdc4ef18c91c6270aa94c75",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08a6f859991c488ca51edf34d52bf97c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6c41c507db448b9bb4a0672b0b7b41e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"e42633e825c74a8f938becf54b7cb910",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35c53625d4ef40428cc1d6f7b5413977",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":390,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"bf83edf0006f47db986ec52f42b8f159",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e224e610689040afa1cf04f66af98792",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open index in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"index.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}},
{
                  "id":"5e9fbfa5a74f4e7e821e4f4d8b51a5c2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x47000000},
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"769794f3d27349f885f6d475c0d1894b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open customer in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"customer.jsp",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u8.png"}}]},
{
              "id":"0bb74550b6a5428eb117921f3fe594cb",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":50},
                "size":{
                  "width":130,
                  "height":142},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"583f471876b64282a34b005aa2c86d30",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4319c11cabc048fdb6504c07d05930c3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2e822343503e413fa60a99e8146e9e64",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open payment in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"payment.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"5bdbb87646b846a2b6cb55a9be517055",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":130,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"40782b77943045198f84e4d9217a7078",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":130,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open inventory in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"inventory.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u18.png"}},
{
                      "id":"eda24422603d4ab8b65b89d62226cad6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":130,
                          "height":50},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a04427f545e24092ae3dd3182179b832",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":130,
                              "height":50},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open newcustomer in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"newcustomer.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u14.png"}}]}],
              "parentCellId":"08a6f859991c488ca51edf34d52bf97c"},
{
              "id":"3607c6ebaa694bedb1ac03bdcb0b8095",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":50},
                "size":{
                  "width":131,
                  "height":171},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4b8a767770e46bf96a5976b96b4be2c",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":131,
                      "height":171}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8aa6df26e9ed44cdab1b1250bab0edb8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "size":{
                          "width":131,
                          "height":41},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"54a665a76c1a4afa9a89b938516d1a5f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "size":{
                              "width":131,
                              "height":41},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open profit in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"profit.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u26.png"}},
{
                      "id":"1ebf997952b845b7ae27075a9f58b9b4",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":41},
                        "size":{
                          "width":131,
                          "height":38},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7625200b43f84b94bcdee88a9f576a2f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":41},
                            "size":{
                              "width":131,
                              "height":38},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open top products in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"top_products.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u28.png"}},
{
                      "id":"861a5289aab84f84967bacd5157e1ab8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":79},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"180e91a3cdd847b983eb1e0a24e51370",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":79},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open comparison in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"comparison.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u30.png"}},
{
                      "id":"bda977d72f824eca8491c3102df05afc",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x47000000},
                        "location":{
                          "x":0,
                          "y":125},
                        "size":{
                          "width":131,
                          "height":46},
                        "limbo":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a4c57cc6153249edbca035d778b8e0aa",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0x47000000},
                            "location":{
                              "x":0,
                              "y":125},
                            "size":{
                              "width":131,
                              "height":46},
                            "limbo":false,
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"Case 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"Open businese in Current Window",
                                  "target":{
                                    "targetType":"page",
                                    "url":"businese.jsp",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/index/u32.png"}}]}],
              "parentCellId":"e42633e825c74a8f938becf54b7cb910"}]}]}},
  "masters":{
},
  "objectPaths":{
    "021a4f6c210d4ed8b58eb6d77da6e99c":{
      "scriptId":"u0"},
    "8443e34bf0054254818947da6f02324d":{
      "scriptId":"u1"},
    "9019ed2b6f904be58f5267b87e6784c4":{
      "scriptId":"u2"},
    "8dad415a7e9d43288538dc69ef7bf3e9":{
      "scriptId":"u3"},
    "1768dd40f4b144ad8b2ff40c195e92ec":{
      "scriptId":"u4"},
    "dc32025c1cc347bea9c5fbb2bd6d1a43":{
      "scriptId":"u5"},
    "e0c574147a9d4aabb2805197604f9f95":{
      "scriptId":"u6"},
    "d1e3806fff3d4ec7b46f2947aa1c3f56":{
      "scriptId":"u7"},
    "8af107abccab45a5bd189abc527f8b40":{
      "scriptId":"u8"},
    "386f4eb3596a45ad8ce10e1751a84d0f":{
      "scriptId":"u9"},
    "734115138f2340c0965c192befb6b041":{
      "scriptId":"u10"},
    "11c11b6fa49445a89f5d30199598b231":{
      "scriptId":"u11"},
    "14ad1d4cf0f346cb83f1955f89a9f6d0":{
      "scriptId":"u12"},
    "0074b7fe3427435db46f5bf542205bd1":{
      "scriptId":"u13"},
    "b359ff0f4f714edbb5caf59ce16c4c2a":{
      "scriptId":"u14"},
    "37b2e47a0d3443c4bfc9336d74ea216a":{
      "scriptId":"u15"},
    "99f4b2db0ba446d5affa0df2224a63cc":{
      "scriptId":"u16"},
    "3f211c640e55469385bc48c94fbce78d":{
      "scriptId":"u17"},
    "808e053edff04e8e85a86616d08bebcc":{
      "scriptId":"u18"},
    "39b1b0fc98f943b0971e7ed84e80a0f2":{
      "scriptId":"u19"},
    "b6236dc009204288bcae959023ae006a":{
      "scriptId":"u20"},
    "53b8a928cb7749ceb6406a9a4995564c":{
      "scriptId":"u21"},
    "47c75a92c1f446edb935b5af9bcf2b81":{
      "scriptId":"u22"},
    "5a926baae1304c108b7380a8781b41b6":{
      "scriptId":"u23"},
    "f929236679514faeb58aa1d0b22ed8c2":{
      "scriptId":"u24"},
    "6b0adf9760554b608118bab82c1419aa":{
      "scriptId":"u25"},
    "b1ef775180ff49ad8ae3af2ddbd7846e":{
      "scriptId":"u26"},
    "44c94fd4a2164493aca4890695d4a9f9":{
      "scriptId":"u27"},
    "6797ae510511467ab9d0a0067224f281":{
      "scriptId":"u28"},
    "dfe83ecd58834a87b03880fabe7dc492":{
      "scriptId":"u29"},
    "270952f1e2744b07a206afb36cb42369":{
      "scriptId":"u30"},
    "291bf558688447fdba93102be29066e2":{
      "scriptId":"u31"},
    "7e3d2e228a9b457bbe5f42378f96b16d":{
      "scriptId":"u32"},
    "3573608c24274f0a9c53db4585793704":{
      "scriptId":"u33"},
    "81015a871e5946e2b31e7166698bacdd":{
      "scriptId":"u34"},
    "b78672a624484898a65c989cb460d29f":{
      "scriptId":"u35"},
    "19923be73a2e467c974c0b261b3481e3":{
      "scriptId":"u36"},
    "8b2b74c237f24cc7b86c19e8a8e3e283":{
      "scriptId":"u37"},
    "b6766a0379ee4c58b3ffdd20ffdc7cb1":{
      "scriptId":"u38"},
    "2b345043e60449cdb8656cc997afa23a":{
      "scriptId":"u39"},
    "21083065d77b4fcea24240cf77d312f9":{
      "scriptId":"u40"},
    "48d5ceeda7884241bfca46483d16a8ed":{
      "scriptId":"u41"},
    "e3a3ba5be84a4623abd2eaee9e709a1e":{
      "scriptId":"u42"},
    "4601a111cae94bd6b0ab8bd8fb126e29":{
      "scriptId":"u43"},
    "1ee79bd3acdc4ef18c91c6270aa94c75":{
      "scriptId":"u44"},
    "bf83edf0006f47db986ec52f42b8f159":{
      "scriptId":"u45"},
    "e224e610689040afa1cf04f66af98792":{
      "scriptId":"u46"},
    "5e9fbfa5a74f4e7e821e4f4d8b51a5c2":{
      "scriptId":"u47"},
    "769794f3d27349f885f6d475c0d1894b":{
      "scriptId":"u48"},
    "08a6f859991c488ca51edf34d52bf97c":{
      "scriptId":"u49"},
    "e6c41c507db448b9bb4a0672b0b7b41e":{
      "scriptId":"u50"},
    "e42633e825c74a8f938becf54b7cb910":{
      "scriptId":"u51"},
    "35c53625d4ef40428cc1d6f7b5413977":{
      "scriptId":"u52"},
    "0bb74550b6a5428eb117921f3fe594cb":{
      "scriptId":"u53"},
    "583f471876b64282a34b005aa2c86d30":{
      "scriptId":"u54"},
    "4319c11cabc048fdb6504c07d05930c3":{
      "scriptId":"u55"},
    "2e822343503e413fa60a99e8146e9e64":{
      "scriptId":"u56"},
    "5bdbb87646b846a2b6cb55a9be517055":{
      "scriptId":"u57"},
    "40782b77943045198f84e4d9217a7078":{
      "scriptId":"u58"},
    "eda24422603d4ab8b65b89d62226cad6":{
      "scriptId":"u59"},
    "a04427f545e24092ae3dd3182179b832":{
      "scriptId":"u60"},
    "3607c6ebaa694bedb1ac03bdcb0b8095":{
      "scriptId":"u61"},
    "f4b8a767770e46bf96a5976b96b4be2c":{
      "scriptId":"u62"},
    "8aa6df26e9ed44cdab1b1250bab0edb8":{
      "scriptId":"u63"},
    "54a665a76c1a4afa9a89b938516d1a5f":{
      "scriptId":"u64"},
    "1ebf997952b845b7ae27075a9f58b9b4":{
      "scriptId":"u65"},
    "7625200b43f84b94bcdee88a9f576a2f":{
      "scriptId":"u66"},
    "861a5289aab84f84967bacd5157e1ab8":{
      "scriptId":"u67"},
    "180e91a3cdd847b983eb1e0a24e51370":{
      "scriptId":"u68"},
    "bda977d72f824eca8491c3102df05afc":{
      "scriptId":"u69"},
    "a4c57cc6153249edbca035d778b8e0aa":{
      "scriptId":"u70"}}});